print help when no arg and run only as root

diff --git a/cup b/cup
--- a/cup
+++ b/cup
@@ -253,35 +253,6 @@ function on_boot() {
 	esac
 }
 
-function main() {
-	while getopts ':vid' ARG; do
-		case "$ARG" in
-			v) export CUP_VERBOSE=true ;;
-			d) set -x ;;
-			?) break ;;
-		esac
-	done
-	shift $(expr $OPTIND - 1)
-
-	SUBCOMMAND="$1"
-	shift
-
-	fetch_state
-	gather_info
-	case $SUBCOMMAND in
-		info) print_info $@ ;;
-		help) print_help $@ ;;
-		update) do_update $@ ;;
-		boot) on_boot $@ ;;
-		"") print_help $@ ;;
-		*)
-			echo "Error: unknown subcommand: $SUBCOMMAND"
-			print_help
-		;;
-	esac
-	save_state
-}
-
 function generate_chromebook_its() {
 
 image=$1
@@ -350,4 +321,40 @@ cat <<-ITS_FOOTER_END
 ITS_FOOTER_END
 }
 
-main $@
+if [ "$USER" != "root" ]; then
+	echo "This program must be ran as root"
+	exit 1
+fi
+
+if [ "$?" = "0" ]; then
+	print_help
+	exit 1
+fi
+
+while getopts ':vd' ARG; do
+	case "$ARG" in
+		v) export CUP_VERBOSE=true ;;
+		d) set -x ;;
+		?) break ;;
+	esac
+done
+shift $(expr $OPTIND - 1)
+unset OPTIND
+
+SUBCOMMAND="$1"
+shift
+
+fetch_state
+gather_info
+case $SUBCOMMAND in
+	info) print_info $@ ;;
+	help) print_help $@ ;;
+	update) do_update $@ ;;
+	boot) on_boot $@ ;;
+	"") print_help $@ ;;
+	*)
+		echo "Error: unknown subcommand: $SUBCOMMAND"
+		print_help
+	;;
+esac
+save_state
